'use client';

import { createClient } from '@supabase/supabase-js';
import { useAuth, useUser } from '@clerk/nextjs';
import { useState } from 'react';

export const AuthTest = () => {
  const { getToken } = useAuth();
  const { user } = useUser();
  const [testResult, setTestResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const testAuth = async () => {
    setLoading(true);
    try {
      console.log('🔍 Testing Clerk-Supabase integration...');
      
      // ✅ Get JWT token from Clerk using your template
      const clerkToken = await getToken({ template: 'supabase' });
      
      if (!clerkToken) {
        setTestResult({ error: 'No JWT token generated by Clerk' });
        setLoading(false);
        return;
      }

      console.log('✅ Clerk token generated successfully');

      // ✅ Create Supabase client with Clerk token
      const supabase = createClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        {
          global: {
            fetch: async (url, options = {}) => {
              const headers = new Headers(options?.headers);
              headers.set('Authorization', `Bearer ${clerkToken}`);
              return fetch(url, { ...options, headers });
            },
          },
        }
      );

      // ✅ Test authentication
      const { data, error } = await supabase.rpc('test_authorization_header');
      
      console.log('🔍 Supabase auth test result:', { data, error });
      
      setTestResult({
        success: true,
        authData: data,
        error: error?.message
      });

    } catch (error: any) {
      console.error('❌ Test error:', error);
      setTestResult({ error: error.message });
    } finally {
      setLoading(false);
    }
  };

  if (!user) {
    return (
      <div className="p-4 border rounded bg-yellow-50">
        <p>Please sign in to test authentication</p>
      </div>
    );
  }

  return (
    <div className="p-4 border rounded bg-green-50">
      <h3 className="font-bold mb-2">🔍 Clerk-Supabase Integration Test</h3>
      <p className="text-sm mb-4">
        ✅ Supabase: Clerk integration enabled<br/>
        ✅ User: {user.primaryEmailAddress?.emailAddress}
      </p>
      
      <button 
        onClick={testAuth}
        disabled={loading}
        className="bg-green-600 text-white px-4 py-2 rounded mb-4 disabled:opacity-50"
      >
        {loading ? 'Testing...' : 'Test Authentication'}
      </button>
      
      {testResult && (
        <div className="mt-4 p-3 bg-white rounded border">
          <h4 className="font-semibold mb-2">Test Result:</h4>
          <pre className="text-xs overflow-auto">
            {JSON.stringify(testResult, null, 2)}
          </pre>
        </div>
      )}
    </div>
  );
}; 